#!/usr/bin/env python
#
# ***** BEGIN GPL LICENSE BLOCK *****
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# The Original Code is Copyright (C) 2014, Blender Foundation
# All rights reserved.
#
# The Original Code is: all of this file.
#
# Contributor(s): Lukas Toenne.
#
# ***** END GPL LICENSE BLOCK *****

Import ('env')

sources = env.Glob('*.cpp')

incs = [
    '.',
    '../',
    '../intern',
    '../util',
    '../../blenkernel',
    '../../blenlib',
    '../../makesdna',
    '../../makesrna',
    '../../../../intern/guardedalloc',
    ]

incs += Split(env['BF_OPENEXR_INC'])

defs = []

if env['WITH_BF_INTERNATIONAL']:
    defs.append('WITH_INTERNATIONAL')

if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw', 'linuxcross', 'win64-vc', 'win64-mingw'):
    incs.append(env['BF_PTHREADS_INC'])

incs.append(env['BF_OPENEXR_INC'])
incs.append(env['BF_ALEMBIC_INC'])

if not env['WITH_BF_CPP11']:
    incs.append(env['BF_BOOST_INC'])

defs.append('WITH_ALEMBIC')

env.BlenderLib('bf_pointcache_alembic', sources, incs, defines=defs, libtype=['core','player'], priority=[901, 901])
